stages:
- deploy

Deploy to Heroku:
  stage: deploy
  image: ruby:latest
  only:
  - main
  script:
  - gem install dpl
  - dpl --provider=heroku --app=asepfsw9 --api-key=814a6785-840d-4ea2-a8c5-beea3977c295